package com.rivet.service;

import com.rivet.domain.entity.Asset;
import com.rivet.domain.entity.User;
import com.rivet.domain.repository.AssetRepository;
import com.rivet.exception.ResourceNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

/**
 * Service for Asset (Equipment) operations.
 * Implements fuzzy matching and intelligent equipment creation.
 */
@Service
@Transactional
public class AssetService {

    @Autowired
    private AssetRepository assetRepository;

    /**
     * Find asset by ID.
     */
    public Asset findById(UUID id) {
        return assetRepository.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("Asset", "id", id));
    }

    /**
     * Find asset by equipment number.
     */
    public Asset findByEquipmentNumber(String equipmentNumber) {
        return assetRepository.findByEquipmentNumber(equipmentNumber)
            .orElseThrow(() -> new ResourceNotFoundException("Asset", "equipmentNumber", equipmentNumber));
    }

    /**
     * Find all assets with pagination.
     */
    public Page<Asset> findAll(Pageable pageable) {
        return assetRepository.findAll(pageable);
    }

    /**
     * Search assets by query string (searches across manufacturer, model, serial, location).
     */
    public Page<Asset> searchAssets(String query, Pageable pageable) {
        return assetRepository.searchAssets(query, pageable);
    }

    /**
     * Find assets by owner.
     */
    public Page<Asset> findByOwner(User owner, Pageable pageable) {
        return assetRepository.findByOwner(owner, pageable);
    }

    /**
     * Create new asset.
     * Equipment number is auto-generated by database trigger.
     */
    public Asset createAsset(Asset asset) {
        // Equipment number will be auto-generated by trigger
        asset.setEquipmentNumber(null);
        return assetRepository.save(asset);
    }

    /**
     * Match or create asset (fuzzy matching logic from Python).
     *
     * 3-step matching:
     * 1. Exact serial match → return existing
     * 2. Fuzzy match manufacturer+model (85%+) → return match
     * 3. Create new asset
     */
    public Asset matchOrCreateAsset(String manufacturer, String modelNumber, String serialNumber, User owner) {
        // Step 1: Exact serial match
        if (serialNumber != null && !serialNumber.isEmpty()) {
            Asset existingBySerial = assetRepository.findBySerialNumber(serialNumber).orElse(null);
            if (existingBySerial != null) {
                return existingBySerial;
            }
        }

        // Step 2: Fuzzy match on manufacturer + model
        if (manufacturer != null && modelNumber != null) {
            List<Asset> candidates = assetRepository.findByManufacturerAndModel(manufacturer, modelNumber);
            if (!candidates.isEmpty()) {
                // For simplicity, return first match
                // In production, implement actual fuzzy matching with similarity threshold
                return candidates.get(0);
            }
        }

        // Step 3: Create new asset
        Asset newAsset = Asset.builder()
            .manufacturer(manufacturer)
            .modelNumber(modelNumber)
            .serialNumber(serialNumber)
            .owner(owner)
            .criticality(Asset.CriticalityLevel.MEDIUM)
            .workOrderCount(0)
            .totalDowntimeHours(0.0f)
            .build();

        return assetRepository.save(newAsset);
    }

    /**
     * Update asset.
     */
    public Asset updateAsset(UUID id, Asset updatedAsset) {
        Asset asset = findById(id);

        // Update fields
        if (updatedAsset.getManufacturer() != null) {
            asset.setManufacturer(updatedAsset.getManufacturer());
        }
        if (updatedAsset.getModelNumber() != null) {
            asset.setModelNumber(updatedAsset.getModelNumber());
        }
        if (updatedAsset.getSerialNumber() != null) {
            asset.setSerialNumber(updatedAsset.getSerialNumber());
        }
        if (updatedAsset.getLocation() != null) {
            asset.setLocation(updatedAsset.getLocation());
        }
        if (updatedAsset.getCriticality() != null) {
            asset.setCriticality(updatedAsset.getCriticality());
        }
        if (updatedAsset.getDescription() != null) {
            asset.setDescription(updatedAsset.getDescription());
        }

        return assetRepository.save(asset);
    }

    /**
     * Delete asset.
     */
    public void deleteAsset(UUID id) {
        Asset asset = findById(id);
        assetRepository.delete(asset);
    }

    /**
     * Find high-maintenance assets (work order count above threshold).
     */
    public List<Asset> findHighMaintenanceAssets(int threshold) {
        return assetRepository.findHighMaintenanceAssets(threshold);
    }

    /**
     * Find assets needing maintenance.
     */
    public List<Asset> findAssetsNeedingMaintenance(int daysSinceLastMaintenance) {
        return assetRepository.findAssetsNeedingMaintenance(daysSinceLastMaintenance);
    }
}
