package com.rivet.service;

import com.rivet.domain.entity.Asset;
import com.rivet.domain.entity.User;
import com.rivet.domain.entity.WorkOrder;
import com.rivet.domain.repository.WorkOrderRepository;
import com.rivet.exception.ResourceNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Service for WorkOrder operations.
 * Implements equipment-first architecture - all work orders MUST link to equipment.
 */
@Service
@Transactional
public class WorkOrderService {

    @Autowired
    private WorkOrderRepository workOrderRepository;

    @Autowired
    private AssetService assetService;

    /**
     * Find work order by ID.
     */
    public WorkOrder findById(UUID id) {
        return workOrderRepository.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("WorkOrder", "id", id));
    }

    /**
     * Find work order by work order number.
     */
    public WorkOrder findByWorkOrderNumber(String workOrderNumber) {
        return workOrderRepository.findByWorkOrderNumber(workOrderNumber)
            .orElseThrow(() -> new ResourceNotFoundException("WorkOrder", "workOrderNumber", workOrderNumber));
    }

    /**
     * Find all work orders with pagination.
     */
    public Page<WorkOrder> findAll(Pageable pageable) {
        return workOrderRepository.findAllByOrderByCreatedAtDesc(pageable);
    }

    /**
     * Find work orders by user.
     */
    public Page<WorkOrder> findByUser(User user, Pageable pageable) {
        return workOrderRepository.findByUser(user, pageable);
    }

    /**
     * Find work orders by equipment.
     */
    public Page<WorkOrder> findByEquipment(Asset equipment, Pageable pageable) {
        return workOrderRepository.findByEquipment(equipment, pageable);
    }

    /**
     * Find work orders by status.
     */
    public Page<WorkOrder> findByStatus(WorkOrder.WorkOrderStatus status, Pageable pageable) {
        return workOrderRepository.findByStatus(status, pageable);
    }

    /**
     * Search work orders.
     */
    public Page<WorkOrder> searchWorkOrders(String query, Pageable pageable) {
        return workOrderRepository.searchWorkOrders(query, pageable);
    }

    /**
     * Create work order.
     * If equipment is not provided, attempts to match/create from equipment details.
     * Work order number is auto-generated by database trigger.
     */
    public WorkOrder createWorkOrder(WorkOrder workOrder) {
        // Equipment-first architecture: MUST have equipment
        if (workOrder.getEquipment() == null) {
            // Try to create/match equipment from denormalized fields
            if (workOrder.getManufacturer() != null) {
                Asset equipment = assetService.matchOrCreateAsset(
                    workOrder.getManufacturer(),
                    workOrder.getModelNumber(),
                    workOrder.getSerialNumber(),
                    workOrder.getUser()
                );
                workOrder.setEquipment(equipment);
            } else {
                throw new IllegalArgumentException("Work order must have equipment or equipment details");
            }
        }

        // Denormalize equipment details for quick access
        Asset equipment = workOrder.getEquipment();
        workOrder.setEquipmentNumber(equipment.getEquipmentNumber());
        workOrder.setManufacturer(equipment.getManufacturer());
        workOrder.setModelNumber(equipment.getModelNumber());
        workOrder.setSerialNumber(equipment.getSerialNumber());
        workOrder.setLocation(equipment.getLocation());

        // Work order number will be auto-generated by trigger
        workOrder.setWorkOrderNumber(null);

        return workOrderRepository.save(workOrder);
    }

    /**
     * Update work order status.
     */
    public WorkOrder updateStatus(UUID id, WorkOrder.WorkOrderStatus status) {
        WorkOrder workOrder = findById(id);
        workOrder.setStatus(status);

        if (status == WorkOrder.WorkOrderStatus.COMPLETED) {
            workOrder.setCompletedAt(Instant.now());
        }

        return workOrderRepository.save(workOrder);
    }

    /**
     * Update work order.
     */
    public WorkOrder updateWorkOrder(UUID id, WorkOrder updatedWorkOrder) {
        WorkOrder workOrder = findById(id);

        // Update fields
        if (updatedWorkOrder.getTitle() != null) {
            workOrder.setTitle(updatedWorkOrder.getTitle());
        }
        if (updatedWorkOrder.getDescription() != null) {
            workOrder.setDescription(updatedWorkOrder.getDescription());
        }
        if (updatedWorkOrder.getStatus() != null) {
            workOrder.setStatus(updatedWorkOrder.getStatus());
            if (updatedWorkOrder.getStatus() == WorkOrder.WorkOrderStatus.COMPLETED) {
                workOrder.setCompletedAt(Instant.now());
            }
        }
        if (updatedWorkOrder.getPriority() != null) {
            workOrder.setPriority(updatedWorkOrder.getPriority());
        }

        return workOrderRepository.save(workOrder);
    }

    /**
     * Delete work order.
     */
    public void deleteWorkOrder(UUID id) {
        WorkOrder workOrder = findById(id);
        workOrderRepository.delete(workOrder);
    }

    /**
     * Get work order statistics.
     */
    public WorkOrderStats getStats(User user) {
        long totalCount = workOrderRepository.countByUser(user);
        long openCount = workOrderRepository.countByStatus(WorkOrder.WorkOrderStatus.OPEN);
        long inProgressCount = workOrderRepository.countByStatus(WorkOrder.WorkOrderStatus.IN_PROGRESS);
        long completedCount = workOrderRepository.countByStatus(WorkOrder.WorkOrderStatus.COMPLETED);

        return new WorkOrderStats(totalCount, openCount, inProgressCount, completedCount);
    }

    /**
     * Find high priority incomplete work orders.
     */
    public List<WorkOrder> findHighPriorityIncomplete() {
        return workOrderRepository.findHighPriorityIncomplete();
    }

    // Inner class for statistics
    public static class WorkOrderStats {
        public final long total;
        public final long open;
        public final long inProgress;
        public final long completed;

        public WorkOrderStats(long total, long open, long inProgress, long completed) {
            this.total = total;
            this.open = open;
            this.inProgress = inProgress;
            this.completed = completed;
        }
    }
}
