import json

# Read deployment info
with open('production_deployment.json', 'r') as f:
    deployment = json.load(f)

workflow_id = deployment['workflow_id']

print("="*80)
print("PRODUCTION WORKFLOW DEPLOYMENT COMPLETE")
print("="*80)
print()
print(f"Workflow Name: {deployment['workflow_name']}")
print(f"Workflow ID: {workflow_id}")
print(f"Webhook URL: {deployment['webhook_url']}")
print()
print("="*80)
print("ACTIVATION REQUIRED")
print("="*80)
print()
print("To activate the production workflow:")
print()
print("1. Open: https://mikecranesync.app.n8n.cloud")
print()
print("2. Navigate to 'Workflows' in the sidebar")
print()
print(f"3. Find 'RIVET URL Validator - PRODUCTION' (ID: {workflow_id})")
print()
print("4. Click the workflow to open it")
print()
print("5. Click the 'Inactive' toggle at the top to activate")
print()
print("6. Verify it shows 'Active'")
print()
print("="*80)
print("TESTING")
print("="*80)
print()
print("After activation, test with:")
print()
print(f"  curl -X POST {deployment['webhook_url']} \\")
print(f'    -H "Content-Type: application/json" \\')
print(f'    -d \'{{"url":"https://www.google.com"}}\'')
print()
print("="*80)
