-- Migration 023: Troubleshooting Tree Drafts
-- Create tables for saving Claude-generated guides as draft troubleshooting trees

-- Create troubleshooting_tree_drafts table
CREATE TABLE IF NOT EXISTS troubleshooting_tree_drafts (
    id SERIAL PRIMARY KEY,

    -- Draft metadata
    equipment_type VARCHAR(255) NOT NULL,
    problem TEXT NOT NULL,

    -- Generated content
    generated_steps JSONB NOT NULL,  -- Array of troubleshooting steps
    original_query TEXT,              -- User's original query/conversation

    -- User tracking
    user_id BIGINT NOT NULL REFERENCES technicians(telegram_id) ON DELETE CASCADE,

    -- Approval workflow
    status VARCHAR(20) NOT NULL DEFAULT 'draft',  -- draft, approved, rejected
    approved_by BIGINT REFERENCES technicians(telegram_id),
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,

    -- Tree conversion
    tree_id INTEGER REFERENCES troubleshooting_trees(id),  -- Set when approved

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT valid_status CHECK (status IN ('draft', 'approved', 'rejected'))
);

-- Create troubleshooting_trees table if not exists (for tree storage after approval)
CREATE TABLE IF NOT EXISTS troubleshooting_trees (
    id SERIAL PRIMARY KEY,
    equipment_type VARCHAR(255) NOT NULL,
    problem VARCHAR(500) NOT NULL,
    tree_data JSONB NOT NULL,  -- Full tree structure in JSON format
    created_by BIGINT REFERENCES technicians(telegram_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    usage_count INTEGER DEFAULT 0,
    UNIQUE(equipment_type, problem)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_drafts_status ON troubleshooting_tree_drafts(status);
CREATE INDEX IF NOT EXISTS idx_drafts_user ON troubleshooting_tree_drafts(user_id);
CREATE INDEX IF NOT EXISTS idx_drafts_created ON troubleshooting_tree_drafts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drafts_equipment ON troubleshooting_tree_drafts(equipment_type);
CREATE INDEX IF NOT EXISTS idx_trees_equipment ON troubleshooting_trees(equipment_type);
CREATE INDEX IF NOT EXISTS idx_trees_active ON troubleshooting_trees(is_active) WHERE is_active = TRUE;

-- Create updated_at trigger function if not exists
CREATE OR REPLACE FUNCTION update_troubleshooting_drafts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for troubleshooting_tree_drafts
CREATE TRIGGER troubleshooting_drafts_updated_at
    BEFORE UPDATE ON troubleshooting_tree_drafts
    FOR EACH ROW
    EXECUTE FUNCTION update_troubleshooting_drafts_updated_at();

-- Trigger for troubleshooting_trees
CREATE TRIGGER troubleshooting_trees_updated_at
    BEFORE UPDATE ON troubleshooting_trees
    FOR EACH ROW
    EXECUTE FUNCTION update_troubleshooting_drafts_updated_at();

-- Comments for documentation
COMMENT ON TABLE troubleshooting_tree_drafts IS 'Draft troubleshooting trees generated by Claude for admin review';
COMMENT ON TABLE troubleshooting_trees IS 'Approved troubleshooting trees for equipment diagnostics';
COMMENT ON COLUMN troubleshooting_tree_drafts.generated_steps IS 'JSON array of troubleshooting steps from Claude';
COMMENT ON COLUMN troubleshooting_tree_drafts.original_query IS 'Original user query that generated this guide';
COMMENT ON COLUMN troubleshooting_trees.tree_data IS 'Complete tree structure with nodes, decisions, and actions';
